[workspace]
members = [".", "crudly-macros"]

[package]
name = "crudly"
version = "0.5.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Derivable crud helpers for sqlx. Write your SELECT, INSERT, UPDATE and DELETE queries once and reuse them for all your entities."
repository = "https://github.com/TimoLehnertz/crudly"
readme = "README.md"
keywords = ["sqlx", "crud", "derive", "macro", "intorow"]
categories = ["database"]
rust-version = "1.94.0"
authors = ["Timo Lehnertz <timolehnertz1@gmail.com>"]
publish = true

[features]
default = ["derive"]
derive = ["dep:crudly-macros"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]
mysql = ["sqlx/mysql"]
all-databases = ["postgres", "sqlite", "mysql"]
json = ["sqlx/json", "crudly-macros/json"]

[dependencies]
sqlx = { version = "0.9", default-features = false, features = ["any"] }
crudly-macros = { path = "crudly-macros", version = "0.5.0", optional = true, default-features = false }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.9", default-features = false, features = [
    "runtime-tokio",
    "derive",
    "sqlite",
    "json",
    "macros",
] }
crudly = { path = ".", features = ["all-databases", "json"] }
serde = "1"
serde_json = "1"
log = "0.4" # For mocking a DB
url = "2" # For mocking a DB
sqlx-core = { version = "0.9", default-features = false }
